mysql:
  build: ./mysql
  volumes:
      - /root/blog/mysql:/var/lib/mysql
# 考虑到安全问题,正式环境时不暴露端口到宿主机
  expose:
      - "3306"
  ports:
      - 5566:3306

# 测试时使用
#  ports:
#   - 13306:3306

my-blog:
  build: ./my-blog
  ports:
   - 80:28080
  volumes:
   - /var/log/blog:/logs
   - /root/blog/upload:/upload
  links:
   - mysql
